### ISSUE TITLE
Wrong Repo Name

### ISSUE THREAD

**Issue by martin-luo** [Weizhuo-Zhang/2019_campus_recruiment#1]

**Comment by Weizhuo-Zhang** [comment]
hahaha，ma ding  ge niu bi, ming zi na li bu dui ma？

**Comment by martin-luo** [comment]
> hahaha，ma ding ge niu bi, ming zi na li bu dui ma？

ray ge niu bi, ying gai shi recruitment

**Comment by Weizhuo-Zhang** [comment]
This is 罗马丁，剪了一个新发型

**Comment by martin-luo** [comment]
> This is 罗马丁，剪了一个新发型

哥太帅了，随口一个双押，佩服佩服
